#!/usr/bin/env ruby

require 'yaml'
require File.expand_path('../../config/environment', __FILE__)

movies = Movie.all.to_yaml
videos = Video.all.to_yaml

movies_file = "#{Rails.root}/samples/movies.yml"
videos_file = "#{Rails.root}/samples/videos.yml"

File.open(movies_file, 'w') {|f| f.write(movies)}

File.open(videos_file, 'w') {|f| f.write(videos)}
